---
apiVersion: v1
kind: Service
metadata:
  name: rodsmutator
  labels:
    app: rodsmutator
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: rodsmutator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rodsmutator
  labels:
    app: rodsmutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rodsmutator
  template:
    metadata:
      name: rodsmutator
      labels:
        app: rodsmutator
    spec:
      containers:
        - name: mutator
          image: rodalbuquerque/mutating-webhook:0.22
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rodsmutator
  labels:
    app: rodsmutator
webhooks:
  - name: rodsmutator.mutatingwebhook.svc.cluster.local
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZFRENDQXZpZ0F3SUJBZ0lVTVJtbktvUjYrVG9Vd0xqNFZwSnI4WFkzWEo0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZjbTlrYzIxMWRHRjBiM0l1YlhWMFlYUnBibWQzWldKb2IyOXJMbk4yWXpBZQpGdzB5TXpBNE1EWXlNVFU0TkRoYUZ3MHlOREE0TURVeU1UVTRORGhhTUNveEtEQW1CZ05WQkFNTUgzSnZaSE50CmRYUmhkRzl5TG0xMWRHRjBhVzVuZDJWaWFHOXZheTV6ZG1Nd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUMKRHdBd2dnSUtBb0lDQVFEVmY1RTJCSkhaa0s0S0ZzNGdoRXFCY2FEK3MzTlB3TlJ4dnJYbytGa2l2eTFIRm9zcAo0Y1dsMFlxSTVwa0J4d0VFS2JGQjVMdm4ySHpWRVl6Qjh3YnVRTTVaa3QyYWkyczlTL0VoUnZtWVZJRm15bUNGCmxlekFxSDU1RGdPMndlRUd2ajE0SGNsNUZWeEloOHU0V3RQWFgvaXp2cjBadWtleDlCU2FxUHFVRnhrelhCZjkKbUh4MnQwdlV0NlZDTmhZdHB6TlpSRDVoM21HNHY0VHI1NXBUc1pHeDJ2L1R0Y0RoUlk2VnJDcFE3RjVWRVNNRApCUmNBZy9UUk5YMHROcUVJbzYrajFJblNNbjlKNTFWRlhick1oeFI0WWRmOVl5NjN0UUl1dXJ2Z3dUMmd0UlVMCndrUzArRjA1NUUxZ0JGL09FdTJoWFljZk1TWEI3S2hBOExDUjBxOEpFRzJyeVR4a2pRTW01WGtDT0pHbjBqNHAKUXdKa2JOLy9UNkE1QlVKYjVoSENGUGdxLzQzZnoxQy8vUlFETW9mU1dNZlRydGJCNTgyWFNuL1RSNW1ON2Y2YQpqdmlqQTZ0NXZpNEllNkFlSTBDSkZkWi81V3JWblZaSGhFTTVwc1FIOFYwQ2MvYjNoQlF5QVU3d0puVHUxaDdHCjN4SVIwLzFhQkMvQ05YSVViZzB3RHc1b1djWld1NUxuWGtVUXB6TGYvbXdzWC9ndVNtZVdwT1NidUlick5odGoKQ2NsT1ZmWllEVHA0ZE5UZFJuTHJsR0VKbXBXK2JWdk0xSTBkRmp1NWhCK2xzb3ZZS3JIRnE5TFJTcitWTEo2WgpueUpMSjJMY3JyeHdpeWhzWm54SVE2R3NualNMWGV0U0hYN212Tlpsb2RxdEdUU1hLZ0hsbUZXQ3p3SURBUUFCCm95NHdMREFxQmdOVkhSRUVJekFoZ2g5eWIyUnpiWFYwWVhSdmNpNXRkWFJoZEdsdVozZGxZbWh2YjJzdWMzWmoKTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCQVhVT3RSZWZjY2xwR2RqRWRpRHlKQTN1QmRXWVJtS2luS2djdAphM2UzdHV1VWFjTHRHeGJocUxGRXFFRTFNRDZENE0vbnRtN2MwWnIySkpFMFNJZUFwU1E2d0lZcjJ3azhnODZ5CmlpbmJtc0lwUjYzYTk3ZXhOYlBNaUpOMG5yZW5HZ0pacE9nb21VWG5SS3hnc3RFZXNpeGhaa0NQUHhDZXYzNG4KbDdwZE13TEhtRDNzMW4wbWZ1WFBSdjN2a2xpWFIyWTVDZElicXBUTWhIVEthb2VubjFQM3Q0Qy9seHJONkJIcQp6d1Q1UytrRlo2NzdLVXJvQzhmYnhUU05LOHU1VGRvb2JrTGVFVm90SXhSb1crNTg3Zm5rN3FISnpQdnVUS2FqCmxNNHdGeWRmY0JIajVVRWhGd2IwRnhmS2VTdURGRFk0VHJPUnpFd3pPcFNuckFBc0NiWExwVG8yYTdwbmc1V1QKdmRtd21nTXRsdjlNNXdCbmFrdWNISXRVZndKcFpkRmltZ2VaNzFCU2VnenBnU3RWaElwQ0pEWUExRGpaYlB1SQpHTGxGVkdJeExVSzI0c3RTSzRGUHVMWUFybFgwRVRKYWRqZm1FZlBrMGhVMWM0ZGZtMkVYempTMThIaGJVVGNmClZxVEt2T0xIN0lkVUpYWGppQmY5U0dONEc5KzByMnRsbGEvcHVhOFlGcEREM0lseGVVNTFmRkVJUFVoeWhyVVgKd3hKcTVyRkZ5c3FsTFI4bWMzd2ZOY0gzSlpKWWM4LzlYSkNMb3NLQVI4eE1IS0FIZXZoUXlkcGJEYWF2cVk5MwowT1RJd1JZSlg5dlJFclFCQmZoR29PMFk4OC80clRHVGhkNTE0dUVjVVNQQWVBdzJOWmFnUzQvbmhjRG4xQ2lsClZOMWxMdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      service:
        name: rodsmutator
        namespace: mutatingwebhook
        path: "/rodsmutator"
        port: 8443
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["ingresses"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore